### ISSUE TITLE
Unable to destroy cluster after Ctrl+C'ing create cluster

### ISSUE THREAD

**Issue by cdrage** [openshift/installer#1098]
# Version

```console
github.com/openshift/installer  master ✗                                                                                                                                    5h8m ◒  ⍉
▶ bin/openshift-install version
bin/openshift-install unreleased-master-95-g3493e1d227fdcff651b9149b53d058a91511c6ff
```

# Platform (aws|libvirt|openstack):

LIbvirt

# What happened?

Did a `openshift-install create cluster` against a Libvirt instance.

Ctrl+C'd half-way through installation since I thought it had frozen.

Afterwards, tried to destroy the semi-failed cluster and received a segfault:

```sh
github.com/openshift/installer  master ✗                                                                                                                                    5h8m ◒  ⍉
▶ ./bin/openshift-install destroy cluster --log-level debug
DEBUG Deleting libvirt domains
fatal error: unexpected signal during runtime execution                                                                                                                              
[signal SIGSEGV: segmentation violation code=0x1 addr=0xdeadbef7 pc=0x7f1e6f4d23d8]

runtime stack:                                                                                                                                                                       
runtime.throw(0x51de566, 0x2a) 
        /usr/local/go/src/runtime/panic.go:608 +0x72                                
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x2f2                                                                                                                          
                                         
goroutine 1 [syscall]:
runtime.cgocall(0x3dcd920, 0xc0008eb898, 0xc000122dc0)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc0008eb868 sp=0xc0008eb830 pc=0x41de2e
github.com/openshift/installer/vendor/github.com/libvirt/libvirt-go._Cfunc_virDomainFreeWrapper(0xa302910, 0xc000122dc0, 0xc000000000)
        _cgo_gotypes.go:3409 +0x4d fp=0xc0008eb898 sp=0xc0008eb868 pc=0x36c33fd
github.com/openshift/installer/vendor/github.com/libvirt/libvirt-go.(*Domain).Free.func1(0xa302910, 0xc000122dc0, 0x0)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/vendor/github.com/libvirt/libvirt-go/domain.go:864 +0xd2 fp=0xc0008eb8d0 sp=0xc0008eb898 pc=0x3726c12
github.com/openshift/installer/vendor/github.com/libvirt/libvirt-go.(*Domain).Free(0xc0006cac70, 0x0, 0x0)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/vendor/github.com/libvirt/libvirt-go/domain.go:864 +0x4c fp=0xc0008eb940 sp=0xc0008eb8d0 pc=0x36ea23c
github.com/openshift/installer/pkg/destroy/libvirt.deleteDomainsSinglePass(0xc0006cac58, 0xc00095fce0, 0x5739680, 0xc0000ae240, 0xc0008ebb01, 0x0, 0x0)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/pkg/destroy/libvirt/libvirt.go:123 +0x661 fp=0xc0008eba80 sp=0xc0008eb940 pc=0x3d8a251
github.com/openshift/installer/pkg/destroy/libvirt.deleteDomains(0xc0006cac58, 0xc00095fce0, 0x5739680, 0xc0000ae240, 0x0, 0x513a9fb)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/pkg/destroy/libvirt/libvirt.go:81 +0xb9 fp=0xc0008ebac8 sp=0xc0008eba80 pc=0x3d89b89
github.com/openshift/installer/pkg/destroy/libvirt.(*ClusterUninstaller).Run(0xc00091dd10, 0xc0000ae240, 0x5133f85)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/pkg/destroy/libvirt/libvirt.go:62 +0xdb fp=0xc0008ebb30 sp=0xc0008ebac8 pc=0x3d89a4b
main.runDestroyCmd(0x5133f85, 0x1, 0xc00095fc00, 0xc0008ebbe0)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/cmd/openshift-install/destroy.go:50 +0x8c fp=0xc0008ebbf8 sp=0xc0008ebb30 pc=0x3dc2b8c
main.newDestroyClusterCmd.func1(0xc000935680, 0xc00095fac0, 0x0, 0x2)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/cmd/openshift-install/destroy.go:37 +0x73 fp=0xc0008ebc38 sp=0xc0008ebbf8 pc=0x3dc7813
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).execute(0xc000935680, 0xc00095fa80, 0x2, 0x2, 0xc000935680, 0xc00095fa80)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:766 +0x2cc fp=0xc0008ebd28 sp=0xc0008ebc38 pc=0x5c438c
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000934c80, 0x8, 0x0, 0xc000966000)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:852 +0x2fd fp=0xc0008ebe68 sp=0xc0008ebd28 pc=0x5c4f2d
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000934c80, 0xc0008ebed8, 0x1)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:800 +0x2b fp=0xc0008ebe98 sp=0xc0008ebe68 pc=0x5c4c0b
main.installerMain()
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:50 +0x1a8 fp=0xc0008ebf40 sp=0xc0008ebe98 pc=0x3dc49c8
main.main()
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:34 +0x37 fp=0xc0008ebf98 sp=0xc0008ebf40 pc=0x3dc46d7
runtime.main()
        /usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc0008ebfe0 sp=0xc0008ebf98 pc=0x4477c7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0008ebfe8 sp=0xc0008ebfe0 pc=0x473501

goroutine 5 [chan receive]:
github.com/openshift/installer/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x9e6a580)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/openshift/installer/vendor/github.com/golang/glog.init.0
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 22 [select]:
github.com/openshift/installer/pkg/terraform/exec/vendor/go.opencensus.io/stats/view.(*worker).start(0xc0006ce680)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/pkg/terraform/exec/vendor/go.opencensus.io/stats/view/worker.go:152 +0xdd
created by github.com/openshift/installer/pkg/terraform/exec/vendor/go.opencensus.io/stats/view.init.0
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/pkg/terraform/exec/vendor/go.opencensus.io/stats/view/worker.go:29 +0x57

goroutine 23 [chan receive]:
github.com/openshift/installer/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x9e6a640)
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/vendor/k8s.io/klog/klog.go:941 +0x8b
created by github.com/openshift/installer/vendor/k8s.io/klog.init.0
        /home/wikus/seafile/files/dev/go/src/github.com/openshift/installer/vendor/k8s.io/klog/klog.go:403 +0x69
```
# What you expected to happen?

Successfully destroyed cluster

# How to reproduce it (as minimally and precisely as possible)?

```console
$ openshift-install create cluster 
# then Ctrl+C half-way through a libvirt install
$ openshift-install destroy cluster
# error occurs here
```

**Comment by cdrage** [comment]
Fixed the issue by rm -rf the auth, metadata, terraform.tfstate, tls, etc. directories.

However, shouldn't this segfault still shouldn't occur?

**Comment by wking** [comment]
Dup of #590.

/close

**Comment by eparis** [comment]
going to re-open this issue and the problem is libvirt specific.

**Comment by praveenkumar** [comment]
@cdrage Can you please try it again, this is already fixed.

**Comment by zeenix** [comment]
I'm sure I've done this many times just in the recent times and destruction works just fine. But please do re-open if it doesn't work for you still.

/close
