### ISSUE TITLE
dep update fails

### ISSUE THREAD

**Issue by mjudeikis** [openshift/installer#1842]
We are trying to consume `installer` as a package. For this to work we "vendor in" installer, and try to resolve dependencies:

On our repository:
```
[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "v12.1.0"

[[constraint]]
  name = "github.com/openshift/installer"
  # We use HEAD. For the release, this should be pointed to release version
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.4"
```

The error we get from installer repo (after pinning some of the dependencies to match installer repo):
```
(14)  ✗   package sigs.k8s.io/controller-runtime/pkg/scheme does not exist within project sigs.k8s.io/controller-runtime
panic: runtime error: index out of range
```

The same error is raised in master branch of the installer if executed:
```
dep ensure -update -v
```

This comes from the fact that `controller-runtime` repository is not locked, and the current master of the repo is using `kuberentes-14.1`. 

and required:
```
   package sigs.k8s.io/controller-runtime/pkg/scheme does not exist within project sigs.k8s.io/controller-runtime
panic: runtime error: index out of range
```

Some of the packages are not overridden in the installer repo and they are trying to pull `master` and requires `sigs.k8s.io/controller-runtime/pkg/scheme` which is 1.14 artifact. 

After locking :
```
# TODO: Remove this after 1.14 rebase lands
[[override]]
  revision = "12d98582e72927b6cd0123e2b4e819f9341ce62c"
  name = "sigs.k8s.io/controller-runtime"
  source = "https://github.com/kubernetes-sigs/controller-runtime.git"
```

Some other package complains about lack of `pkg/schema`.

I think this can be solved by rebasing to 1.14. 

@asalkeld @crawford @abhinavdahiya

**Comment by mjudeikis** [comment]
And I can see that partially rebase is blocked on cluster-api rebase

**Comment by mjudeikis** [comment]
```
(16)      try github.com/openshift/cluster-api@revert-144-do-not-use-openssl
(16)  ✗   "github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1" contains malformed code: import root "github.com/openshift/cluster-api" is not a prefix for the package's declared canonical path "sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/golang/dep/gps.(*solver).findValidVersion(0xc0002b2700, 0xc000f2b900, 0xc000eb00a0, 0x1, 0x1, 0x0, 0xc000eb00a0)
	/Users/travis/gopath/src/github.com/golang/dep/gps/solver.go:945 +0x4cc
github.com/golang/dep/gps.(*solver).createVersionQueue(0xc0002b2700, 0xc00043df60, 0x20, 0x0, 0x0, 0xc000eb00a0, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/golang/dep/gps/solver.go:902 +0x472
github.com/golang/dep/gps.(*solver).solve(0xc0002b2700, 0xadbda0, 0xc000022158, 0x5, 0xc0000a6568, 0xc0000e7548)
	/Users/travis/gopath/src/github.com/golang/dep/gps/solver.go:505 +0x543
github.com/golang/dep/gps.(*solver).Solve(0xc0002b2700, 0xadbda0, 0xc000022158, 0xeb0a88, 0xc00002e032, 0x24, 0xc000229bc0)
	/Users/travis/gopath/src/github.com/golang/dep/gps/solver.go:440 +0x1eb
main.(*ensureCommand).runDefault(0xc000153766, 0xc0000d0880, 0xc000172680, 0x0, 0x0, 0xc0000cb200, 0xae3c20, 0xc000271260, 0xc00002e004, 0x52, ...)
	/Users/travis/gopath/src/github.com/golang/dep/cmd/dep/ensure.go:281 +0x3fb
main.(*ensureCommand).Run(0xc000153766, 0xc0000d0880, 0xc000172680, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/golang/dep/cmd/dep/ensure.go:218 +0x80e
main.(*Config).Run(0xc000082f00, 0x0)
	/Users/travis/gopath/src/github.com/golang/dep/cmd/dep/main.go:212 +0x111c
main.main()
	/Users/travis/gopath/src/github.com/golang/dep/cmd/dep/main.go:84 +0x636
```

Overall its due to lose vendor packages. When trying to resolve main squashed dep tree - it fails

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/installer/pull/1872/files reduces the surface installer depends on sigs.k8s.io/controller-runtime/pkg/scheme
And as for vendoring installer, you can override the packages too.

/close
