### ISSUE TITLE
signal SIGBUS: bus error code=0x2 when trying to build installer

### ISSUE THREAD

**Issue by jeffsaremi** [openshift/installer#3310]
# Version

```console
$ openshift-install version
-bash: openshift-install: command not found
```

# Platform:
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"

rhel on azure
```

# What happened?
Build problem
```
[jesaremi@rhel-build installer]$ TAGS=libvirt hack/build.sh
+ minimum_go_version=1.13
++ go version
++ cut -d ' ' -f 3
+ current_go_version=go1.13.3
++ version 1.13.3
++ IFS=.
++ printf '%03d%03d%03d\n' 1 13 3
++ unset IFS
++ version 1.13
++ IFS=.
++ printf '%03d%03d%03d\n' 1 13
++ unset IFS
+ '[' 001013003 -lt 001013000 ']'
+ MODE=release
++ git rev-parse --verify 'HEAD^{commit}'
+ GIT_COMMIT=344e38f31fb65dfd27184bee420e6ec0043618b7
++ git describe --always --abbrev=40 --dirty
+ GIT_TAG=unreleased-master-2708-g344e38f31fb65dfd27184bee420e6ec0043618b7
+ GOFLAGS=-mod=vendor
+ LDFLAGS=' -X github.com/openshift/installer/pkg/version.Raw=unreleased-master-2708-g344e38f31fb65dfd27184bee420e6ec0043618b7 -X github.com/openshift/installer/pkg/version.Commit=344e38f31fb65dfd27184bee420e6ec0043618b7'
+ TAGS=libvirt
+ OUTPUT=bin/openshift-install
+ export CGO_ENABLED=0
+ CGO_ENABLED=0
+ case "${MODE}" in
+ LDFLAGS=' -X github.com/openshift/installer/pkg/version.Raw=unreleased-master-2708-g344e38f31fb65dfd27184bee420e6ec0043618b7 -X github.com/openshift/installer/pkg/version.Commit=344e38f31fb65dfd27184bee420e6ec0043618b7 -s -w'
+ TAGS='libvirt release'
+ test '' '!=' y
+ go generate ./data
go: downloading github.com/shurcooL/vfsgen v0.0.0-20181202132449-6a9ea43bcacd
go: extracting github.com/shurcooL/vfsgen v0.0.0-20181202132449-6a9ea43bcacd
go: downloading github.com/shurcooL/httpfs v0.0.0-20190707220628-8d4bc4ba7749
go: extracting github.com/shurcooL/httpfs v0.0.0-20190707220628-8d4bc4ba7749
go: finding github.com/shurcooL/vfsgen v0.0.0-20181202132449-6a9ea43bcacd
go: finding github.com/shurcooL/httpfs v0.0.0-20190707220628-8d4bc4ba7749
writing assets_vfsdata.go
+ echo 'libvirt release'
+ grep -q libvirt
+ export CGO_ENABLED=1
+ CGO_ENABLED=1
+ go build -mod=vendor -ldflags ' -X github.com/openshift/installer/pkg/version.Raw=unreleased-master-2708-g344e38f31fb65dfd27184bee420e6ec0043618b7 -X github.com/openshift/installer/pkg/version.Commit=344e38f31fb65dfd27184bee420e6ec0043618b7 -s -w' -tags 'libvirt release' -o bin/openshift-install ./cmd/openshift-install
# github.com/openshift/installer/cmd/openshift-install
unexpected fault address 0x7f3ab7493000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f3ab7493000 pc=0x45bbca]

goroutine 1 [running]:
runtime.throw(0x690f25, 0x5)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0008acef0 sp=0xc0008acec0 pc=0x42dc42
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:391 +0x455 fp=0xc0008acf20 sp=0xc0008acef0 pc=0x442be5
runtime.memmove(0x7f3ab3c296a0, 0xc0f570a000, 0x70e9bf5)
        /usr/local/go/src/runtime/memmove_amd64.s:422 +0x50a fp=0xc0008acf28 sp=0xc0008acf20 pc=0x45bbca
cmd/link/internal/ld.(*OutBuf).Write(0xc0006c4000, 0xc0f570a000, 0x70e9bf5, 0xbaf805c, 0x8, 0x0, 0x0)
        /usr/local/go/src/cmd/link/internal/ld/outbuf.go:65 +0xa0 fp=0xc0008acf78 sp=0xc0008acf28 pc=0x5ac560
cmd/link/internal/ld.(*OutBuf).WriteSym(0xc0006c4000, 0xc0bd051720)
        /usr/local/go/src/cmd/link/internal/ld/outbuf.go:159 +0x6c fp=0xc0008acfc8 sp=0xc0008acf78 pc=0x5acd2c
cmd/link/internal/ld.blk(0xc0006c4000, 0xc10d47c000, 0x3085, 0x13ac00, 0xe1876a0, 0x70e9bf5, 0x8771e0, 0x200, 0x200)
        /usr/local/go/src/cmd/link/internal/ld/data.go:786 +0x10f fp=0xc0008ad098 sp=0xc0008acfc8 pc=0x5599af
cmd/link/internal/ld.writeDatblkToOutBuf(0xc0006c2000, 0xc0006c4000, 0xe1876a0, 0x70e9bf5)
        /usr/local/go/src/cmd/link/internal/ld/data.go:825 +0xaf fp=0xc0008ad260 sp=0xc0008ad098 pc=0x559fff
cmd/link/internal/ld.Datblk(...)
        /usr/local/go/src/cmd/link/internal/ld/data.go:808
cmd/link/internal/amd64.asmb(0xc0006c2000)
        /usr/local/go/src/cmd/link/internal/amd64/asm.go:680 +0x186 fp=0xc0008ad2d0 sp=0xc0008ad260 pc=0x5d1ce6
cmd/link/internal/ld.Main(0x84bdc0, 0x10, 0x20, 0x1, 0x7, 0x10, 0x69ac6c, 0x1b, 0x697753, 0x14, ...)
        /usr/local/go/src/cmd/link/internal/ld/main.go:262 +0xd5d fp=0xc0008ad428 sp=0xc0008ad2d0 pc=0x5ab5ad
main.main()
        /usr/local/go/src/cmd/link/main.go:65 +0x1d6 fp=0xc0008adf60 sp=0xc0008ad428 pc=0x614616
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc0008adfe0 sp=0xc0008adf60 pc=0x42f5de
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0008adfe8 sp=0xc0008adfe0 pc=0x45a511
```

**Comment by abhinavdahiya** [comment]
Since you building for libvirt, do you have the libvirt devel libs installed? https://github.com/openshift/installer/blob/master/docs/dev/libvirt/README.md

**Comment by jeffsaremi** [comment]
yes i installed it like this:
```
sudo yum install libvirt libvirt-devel libvirt-daemon-kvm qemu-kvm
```
and I can verify:
```
[jesaremi@rhel-build ~]$ sudo yum list libvirt-devel
Loaded plugins: langpacks, product-id, search-disabled-repos
Installed Packages
libvirt-devel.x86_64                          4.5.0-23.el7_7.5                          @rhui-rhel-7-server-rhui-rpms
Available Packages
libvirt-devel.i686                            4.5.0-23.el7_7.5                          rhui-rhel-7-server-rhui-rpms
```

**Comment by cfergeau** [comment]
Is this reproducible? This looks like a golang compiler/linker bug (or a hardware issue)
