### ISSUE TITLE
Invalid memory address or nil pointer dereference when Openstack flavor does not exists

### ISSUE THREAD

**Issue by ppeereb1** [openshift/installer#4333]
# Version
4.6.1

# Platform:
openstack
UP/ & IPI

# What happened?

Set a non existing Openstack flavor in install-config.yaml and try to deploy. It gives an invalid memory address or nil pointer dereference error:

```
openshift-install create manifests --dir <dir>

STDERR:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2208910]
goroutine 1 [running]:
github.com/openshift/installer/pkg/asset/installconfig/openstack/validation.validatePlatformFlavor(0xc00075c540, 0xc000f851d0, 0xc000db4510, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/installer/pkg/asset/installconfig/openstack/validation/platform.go:83 +0xb0
github.com/openshift/installer/pkg/asset/installconfig/openstack/validation.ValidatePlatform(0xc00075c540, 0xc0007c4240, 0xc000f851d0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/installer/pkg/asset/installconfig/openstack/validation/platform.go:25 +0x1ed
github.com/openshift/installer/pkg/asset/installconfig/openstack.Validate(0xc0005a9200, 0x0, 0x0)
	/go/src/github.com/openshift/installer/pkg/asset/installconfig/openstack/validate.go:19 +0x8e
github.com/openshift/installer/pkg/asset/installconfig.(*InstallConfig).platformValidation(0xc000739860, 0x0, 0x0)
	/go/src/github.com/openshift/installer/pkg/asset/installconfig/installconfig.go:188 +0x87
github.com/openshift/installer/pkg/asset/installconfig.(*InstallConfig).finish(0xc000739860, 0xd4f01cb, 0x13, 0x1142, 0xd216b00)
	/go/src/github.com/openshift/installer/pkg/asset/installconfig/installconfig.go:148 +0x234
github.com/openshift/installer/pkg/asset/installconfig.(*InstallConfig).Load(0xc000739860, 0xe7c97e0, 0xc000767180, 0xe8be2a0, 0xc000739860, 0xc000739860)
	/go/src/github.com/openshift/installer/pkg/asset/installconfig/installconfig.go:125 +0x1f0
github.com/openshift/installer/pkg/asset/store.(*storeImpl).load(0xc000781110, 0xe7f3f20, 0xc0007394c0, 0xc00003dc2c, 0x4, 0xc00003dc2c, 0x4, 0x0)
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:264 +0x455
github.com/openshift/installer/pkg/asset/store.(*storeImpl).load(0xc000781110, 0xe7f3ee0, 0xc000739440, 0xd4838c4, 0x2, 0xd4838c4, 0x2, 0x0)
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:247 +0x2d7
github.com/openshift/installer/pkg/asset/store.(*storeImpl).load(0xc000781110, 0xe7f4260, 0x154c3500, 0x0, 0x0, 0x2, 0x2, 0xe740e60)
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:247 +0x2d7
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc000781110, 0xe7f4260, 0x154c3500, 0x0, 0x0, 0x40b4e5, 0xbf8cde0)
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:201 +0xa3a
github.com/openshift/installer/pkg/asset/store.(*storeImpl).Fetch(0xc000781110, 0xe7f4260, 0x154c3500, 0x1547f8e0, 0x4, 0x4, 0x1100000000000000, 0xed7320de1)
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:77 +0x4b
main.runTargetCmd.func1(0x7ffff3e1fe06, 0x30, 0xc0007393a0, 0xc000780f00)
	/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:172 +0x135
main.runTargetCmd.func2(0x1548b280, 0xc000739160, 0x0, 0x2)
	/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:199 +0xb5
github.com/spf13/cobra.(*Command).execute(0x1548b280, 0xc000739100, 0x2, 0x2, 0x1548b280, 0xc000739100)
	/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:844 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000524000, 0xc000df5e58, 0x1, 0x1)
	/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:945 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:885
main.installerMain()
	/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:63 +0x2b8
main.main()
	/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:43 +0xcf
```

# What you expected to happen?
A nice error that the provided flavor does not exists.

**Comment by pierreprinetti** [comment]
Tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1887863
Fix proposed in https://github.com/openshift/installer/pull/4289

Thanks!
/close

**Comment by krauthosting** [comment]
For clarification `4.6` also just crashes without error on missing `computeFlavor`.
That has been deprecated and replaced with `defaultMachinePlatform` in `4.7`.
The fix should be backported against current stable release of openshift-install:

```
bin/openshift-install 4.6.4
built from commit 6e02d049701437fa81521fe981405745a62c86c5
release image quay.io/openshift-release-dev/ocp-release@sha256:6681fc3f83dda0856b43cecd25f2d226c3f90e8a42c7144dbc499f6ee0a086fc
```

**Comment by pierreprinetti** [comment]
@krauthosting 
Thank you. Tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1931814
