### ISSUE TITLE
openshift 4.7 fails similar to #3579  SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1895ca1

### ISSUE THREAD

**Issue by olafWW** [openshift/installer#5109]
# Version 4.7

$ openshift-install version
[root@r84n1 cluster]# ./openshift-install version
./openshift-install 4.7.19
built from commit 3948d1fe9f04057823b871133085d602e6575067
release image quay.io/openshift-release-dev/ocp-release@sha256:eafdac268e1f65053de423ba4a028e8de5133ab78e7954d76ed838bcf5f4f666

```

# Platform:      baremetal


<!--
Please specify:
* IPI (automated install with `openshift-install`. 
-->

# What happened?

I followed the doc starting here:  https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal.html#prerequisites  and subsequent chapters... 
# What you expected to happen?  
I successfully deployed  all nodes from the USB ISO.
The 3 master nodes from USB ISO came up after reboot and they seem to be configured automatically and came up (after the bootstrap machine was there) 
I can access 3 master and the bootstrap ..by login with ssh core@....    so far that looks not to bad/ok 
but ...
however .. some of the pods are in error state..  (oc get pods -A ) 
additionally , I see the worker nodes also hanging  at boot .- None of the 3 worker nodes is up and running. 


I started my first aid and took  the first broken pod(s) , which is:
[root@r84n1 cluster]# oc get pods -A 
NAMESPACE                                          NAME                                                      READY   STATUS                     RESTARTS   AGE
openshift-apiserver-operator                       openshift-apiserver-operator-57549c9976-bglq2             0/1     Pending                    0          3h6m
openshift-apiserver                                apiserver-865f6bcb5f-czcj2                                1/2     CrashLoopBackOff           9          27m

and 


so [root@r84n1 cluster]# oc logs apiserver-865f6bcb5f-czcj2 -n openshift-apiserver -c openshift-apiserver
Copying system trust bundle
I0727 19:23:04.481909       1 dynamic_serving_content.go:111] Loaded a new cert/key pair for "serving-cert::/var/run/secrets/serving-cert/tls.crt::/var/run/secrets/serving-cert/tls.key"
I0727 19:23:04.804464       1 requestheader_controller.go:244] Loaded a new request header values for RequestHeaderAuthRequestController
I0727 19:23:04.806493       1 audit.go:344] Using audit backend: ignoreErrors<log>
I0727 19:23:04.809923       1 plugins.go:84] Registered admission plugin "NamespaceLifecycle"
I0727 19:23:04.809949       1 plugins.go:84] Registered admission plugin "ValidatingAdmissionWebhook"
I0727 19:23:04.809959       1 plugins.go:84] Registered admission plugin "MutatingAdmissionWebhook"
I0727 19:23:04.812280       1 admission.go:48] Admission plugin "project.openshift.io/ProjectRequestLimit" is not configured so it will be disabled.
I0727 19:23:04.813997       1 plugins.go:158] Loaded 5 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,build.openshift.io/BuildConfigSecretInjector,image.openshift.io/ImageLimitRange,image.openshift.io/ImagePolicy,MutatingAdmissionWebhook.
I0727 19:23:04.814016       1 plugins.go:161] Loaded 8 validating admission controller(s) successfully in the following order: OwnerReferencesPermissionEnforcement,build.openshift.io/BuildConfigSecretInjector,build.openshift.io/BuildByStrategy,image.openshift.io/ImageLimitRange,image.openshift.io/ImagePolicy,quota.openshift.io/ClusterResourceQuota,ValidatingAdmissionWebhook,ResourceQuota.
I0727 19:23:04.821932       1 client.go:360] parsed scheme: "endpoint"
I0727 19:23:04.821960       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://10.0.11.51:2379  <nil> 0 <nil>} {https://10.0.11.52:2379  <nil> 0 <nil>}]
W0727 19:23:04.823628       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.11.52:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.11.52:2379: connect: connection refused". Reconnecting...
W0727 19:23:04.823840       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.11.51:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.11.51:2379: connect: connection refused". Reconnecting...
W0727 19:23:05.824708       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.11.52:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.11.52:2379: connect: connection refused". Reconnecting...
W0727 19:23:05.824787       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.11.51:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.11.51:2379: connect: connection refused". Reconnecting...
W0727 19:23:07.108154       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.11.51:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.11.51:2379: connect: connection refused". Reconnecting...
W0727 19:23:07.584448       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.11.52:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.11.52:2379: connect: connection refused". Reconnecting...
W0727 19:23:09.399649       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.11.51:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.11.51:2379: connect: connection refused". Reconnecting...
W0727 19:23:10.339288       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.11.52:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.11.52:2379: connect: connection refused". Reconnecting...
W0727 19:23:13.213107       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.11.51:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.11.51:2379: connect: connection refused". Reconnecting...
W0727 19:23:13.701980       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.11.52:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.11.52:2379: connect: connection refused". Reconnecting...
W0727 19:23:19.710525       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.11.51:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.11.51:2379: connect: connection refused". Reconnecting...
W0727 19:23:20.234355       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.11.52:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.11.52:2379: connect: connection refused". Reconnecting...
F0727 19:23:24.822212       1 openshift_apiserver.go:379] context deadline exceeded
goroutine 1 [running]:


# How to reproduce it (as minimally and precisely as possible)?

<!--
Please list the full steps required to reproduce the issue.
I claim to followed 1:1 the docs
let me know.. if I should post my haproxy.cfg  here  , but I would claim, the issue is not the loadbalancer.. it seems, that on the end of the master nodes.. nobody answering on etcd port 2379   ???

however.. the IP Address from masters would be 10.0.11.5[1,2,3] and they are all up n running.. don't know.. why I only see worker1 (~.51) and worker2 (~.52) here and if that is already wrong !?

additional .. logged in on the master.. I can not see a service LISTENING on port 2379


[core@master1 ~]$ netstat -an | grep LIS | grep 2379 
[core@master1 ~]$ netstat -an | grep LIS 
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:4180          0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 10.0.11.51:10010        0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:8797          0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:40127           0.0.0.0:*               LISTEN     
tcp        0      0 10.0.11.51:22           10.0.11.41:50352        ESTABLISHED
tcp        0      0 10.129.0.1:59946        172.30.0.1:443          ESTABLISHED
tcp        0      0 127.0.0.1:34430         127.0.0.1:10248         ESTABLISHED
tcp        0      0 10.0.11.51:39974        10.0.11.100:6443        ESTABLISHED
tcp        0      0 10.129.0.1:59892        172.30.0.1:443          ESTABLISHED
tcp        0      0 10.0.11.51:39996        10.0.11.100:6443        ESTABLISHED
tcp        0      0 10.0.11.51:39970        10.0.11.100:6443        ESTABLISHED
tcp        0      0 127.0.0.1:10248         127.0.0.1:34430         ESTABLISHED
tcp        0      0 10.0.11.51:22           10.0.11.41:59262        ESTABLISHED
tcp6       0      0 :::9537                 :::*                    LISTEN     
tcp6       0      0 :::9001                 :::*                    LISTEN     
tcp6       0      0 :::10250                :::*                    LISTEN     
tcp6       0      0 :::9101                 :::*                    LISTEN     
tcp6       0      0 :::29101                :::*                    LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::10256                :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::46621                :::*                    LISTEN     
udp        0      0 10.0.11.51:68           10.0.11.41:67           ESTABLISHED




-->

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by olafWW** [comment]
update:   
the initial ERROR message is now understood..its based, that the master nodes does not get ready
a closer look during the deployment process unveiled the root cause 

core@master1 ~]$ systemctl status machine-config-daemon-firstboot
● machine-config-daemon-firstboot.service - Machine Config Daemon Firstboot
   Loaded: loaded (/etc/systemd/system/machine-config-daemon-firstboot.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2021-07-28 14:43:26 UTC; 14min ago
  Process: 1966 ExecStart=/run/bin/machine-config-daemon firstboot-complete-machineconfig (code=exited, status=2)
  Process: 1965 ExecStartPre=/usr/bin/sh -c sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/*.repo (code=exited, status=2)
 Main PID: 1966 (code=exited, status=2)
      CPU: 36.705s

manually ytarted the program - unveiles the issue 

[core@master1 ~]$ sudo /run/bin/machine-config-daemon firstboot-complete-machineconfig
I0728 14:52:17.145510    2244 rpm-ostree.go:261] Running captured: rpm-ostree status --json
I0728 14:52:17.201525    2244 daemon.go:218] Booted osImageURL:  (47.83.202105220305-0)
I0728 14:52:17.202730    2244 update.go:630] Checking Reconcilable for config mco-empty-mc to rendered-master-3bbe4b469bfd5631739093bb8ab65d58
I0728 14:52:17.204338    2244 update.go:1943] Starting update from mco-empty-mc to rendered-master-3bbe4b469bfd5631739093bb8ab65d58: &{osUpdate:true kargs:false fips:false passwd:false files:false units:false kernelType:false extensions:false}
I0728 14:52:17.207542    2244 update.go:1258] Updating files
I0728 14:52:17.207929    2244 update.go:1331] Deleting stale data
I0728 14:52:17.208968    2244 run.go:18] Running: nice -- ionice -c 3 oc image extract --path /:/run/mco-machine-os-content/os-content-177457748 --registry-config /var/lib/kubelet/config.json quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:07c0cbfed7fb3efdf794535430971f8d78fca8fde8f040ed38bdc5b435075044
I0728 14:55:31.204695    2244 update.go:1821] Updating OS to quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:07c0cbfed7fb3efdf794535430971f8d78fca8fde8f040ed38bdc5b435075044
I0728 14:55:31.204880    2244 rpm-ostree.go:261] Running captured: rpm-ostree status --json
I0728 14:55:31.258563    2244 rpm-ostree.go:184] Current origin is not custom
I0728 14:55:33.166385    2244 rpm-ostree.go:211] Pivoting to: 47.83.202106252242-0 (f228e5682bf91e1b70394d17e57c896d8966a5841bb850806c29060a253eea44)
I0728 14:55:33.167965    2244 rpm-ostree.go:243] Executing rebase from repo path /run/mco-machine-os-content/os-content-177457748/srv/repo with customImageURL pivot://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:07c0cbfed7fb3efdf794535430971f8d78fca8fde8f040ed38bdc5b435075044 and checksum f228e5682bf91e1b70394d17e57c896d8966a5841bb850806c29060a253eea44
I0728 14:55:33.170514    2244 rpm-ostree.go:261] Running captured: rpm-ostree rebase --experimental /run/mco-machine-os-content/os-content-177457748/srv/repo:f228e5682bf91e1b70394d17e57c896d8966a5841bb850806c29060a253eea44 --custom-origin-url pivot://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:07c0cbfed7fb3efdf794535430971f8d78fca8fde8f040ed38bdc5b435075044 --custom-origin-description Managed by machine-config-operator
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1895ca1]

goroutine 1 [running]:
github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).applyOSChanges(0xc0004ce2c0, 0xc0003b7d40, 0xc0000a5520, 0x0, 0x0)
        /go/src/github.com/openshift/machine-config-operator/pkg/daemon/update.go:465 +0x2c1
github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).update(0xc0004ce2c0, 0xc0003b7d40, 0xc0000a5520, 0x0, 0x0)
        /go/src/github.com/openshift/machine-config-operator/pkg/daemon/update.go:712 +0xb58
github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).RunFirstbootCompleteMachineconfig(0xc0004ce2c0, 0x2b51c88, 0xc0000960c0)
        /go/src/github.com/openshift/machine-config-operator/pkg/daemon/daemon.go:555 +0x173
main.runFirstBootCompleteMachineConfig(0x2b06420, 0x2b51c88, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/openshift/machine-config-operator/cmd/machine-config-daemon/firstboot_complete_machineconfig.go:39 +0x16f
main.executeFirstbootCompleteMachineConfig(0x2b06420, 0x2b51c88, 0x0, 0x0)
        /go/src/github.com/openshift/machine-config-operator/cmd/machine-config-daemon/firstboot_complete_machineconfig.go:43 +0x53
github.com/spf13/cobra.(*Command).execute(0x2b06420, 0x2b51c88, 0x0, 0x0, 0x2b06420, 0x2b51c88)
        /go/src/github.com/openshift/machine-config-operator/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2b066c0, 0xc00089ff78, 0x4062c5, 0xc000096058)
        /go/src/github.com/openshift/machine-config-operator/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/openshift/machine-config-operator/vendor/github.com/spf13/cobra/command.go:895
main.main()
        /go/src/github.com/openshift/machine-config-operator/cmd/machine-config-daemon/main.go:27 +0x31
[core@master1 ~]$

**Comment by olafWW** [comment]
I did an strace on the command 
sudo strace /run/bin/machine-config-daemon firstboot-complete-machineconfig

[...] 
openat(10, "system.d", O_RDONLY|O_CLOEXEC) = 11
epoll_ctl(3, EPOLL_CTL_ADD, 11, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=377576632, u64=140445808155832}}) = -1 EPERM (Operation not permitted)
epoll_ctl(3, EPOLL_CTL_DEL, 11, 0xc000bba60c) = -1 EPERM (Operation not permitted)
getdents64(11, /* 9 entries */, 8192)   = 424
getdents64(11, /* 0 entries */, 8192)   = 0
unlinkat(11, "org.freedesktop.resolve1.conf", 0) = 0
unlinkat(11, "org.freedesktop.systemd1.conf", 0) = 0
unlinkat(11, "org.freedesktop.hostname1.conf", 0) = 0
unlinkat(11, "org.freedesktop.login1.conf", 0) = 0
unlinkat(11, "org.freedesktop.portable1.conf", 0) = 0
unlinkat(11, "org.freedesktop.timedate1.conf", 0) = 0
unlinkat(11, "org.freedesktop.locale1.conf", 0) = 0
close(11)                               = 0
unlinkat(10, "system.d", AT_REMOVEDIR)  = 0
unlinkat(10, "system.conf", 0)          = 0
unlinkat(10, "services", 0)             = -1 EISDIR (Is a directory)
newfstatat(10, "services", {st_mode=S_IFDIR|0755, st_size=60, ...}, AT_SYMLINK_NOFOLLOW) = 0
openat(10, "services", O_RDONLY|O_CLOEXEC) = 11
epoll_ctl(3, EPOLL_CTL_ADD, 11, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=377576632, u64=140445808155832}}) = -1 EPERM (Operation not permitted)
epoll_ctl(3, EPOLL_CTL_DEL, 11, 0xc000bba60c) = -1 EPERM (Operation not permitted)
getdents64(11, /* 3 entries */, 8192)   = 104
getdents64(11, /* 0 entries */, 8192)   = 0
unlinkat(11, "org.freedesktop.systemd1.service", 0) = 0
close(11)                               = 0
unlinkat(10, "services", AT_REMOVEDIR)  = 0
unlinkat(10, "session.conf", 0)         = 0
unlinkat(10, "interfaces", 0)           = -1 EISDIR (Is a directory)
newfstatat(10, "interfaces", {st_mode=S_IFDIR|0755, st_size=40, ...}, AT_SYMLINK_NOFOLLOW) = 0
openat(10, "interfaces", O_RDONLY|O_CLOEXEC) = 11
epoll_ctl(3, EPOLL_CTL_ADD, 11, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=377576632, u64=140445808155832}}) = -1 EPERM (Operation not permitted)
epoll_ctl(3, EPOLL_CTL_DEL, 11, 0xc000bba60c) = -1 EPERM (Operation not permitted)
epoll_pwait(3, [], 128, 0, NULL, 1)     = 0
futex(0x2b1f378, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x2b1f278, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc00006f148, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2370, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2370, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2370, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2370, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2370, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2370, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 1
[....] ~ 300 lines [...] 
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2370, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2370, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2370, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2370, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 1
epoll_pwait(3, [], 128, 0, NULL, 1262066214721) = 0
epoll_pwait(3, [{EPOLLIN, {u32=45423592, u64=45423592}}], 128, 467, NULL, 0) = 1
read(4, "\0", 16)                       = 1
epoll_pwait(3, [], 128, 0, NULL, 1262071469701) = 0
epoll_pwait(3, [{EPOLLIN, {u32=45423592, u64=45423592}}], 128, 150, NULL, 0) = 1
read(4, "\0", 16)                       = 1
futex(0x2b1fc88, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
unlinkat(14, "GObject.cpython-36.pyc", 0) = 0
futex(0x2b1fc88, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x2b1f390, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2b1f278, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x2b1fc88, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
madvise(0xc000e00000, 2097152, MADV_NOHUGEPAGE) = 0
madvise(0xc000efa000, 8192, MADV_FREE)  = 0
futex(0x2b1fc88, FUTEX_WAIT_PRIVATE, 0, NULLpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1895ca1]

goroutine 1 [running]:
github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).applyOSChanges(0xc0001a8840, 0xc0001e2000, 0xc0000b1040, 0x0, 0x0)
        /go/src/github.com/openshift/machine-config-operator/pkg/daemon/update.go:465 +0x2c1
github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).update(0xc0001a8840, 0xc0001e2000, 0xc0000b1040, 0x0, 0x0)
        /go/src/github.com/openshift/machine-config-operator/pkg/daemon/update.go:712 +0xb58
github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).RunFirstbootCompleteMachineconfig(0xc0001a8840, 0x2b51c88, 0xc0001000c0)
        /go/src/github.com/openshift/machine-config-operator/pkg/daemon/daemon.go:555 +0x173
main.runFirstBootCompleteMachineConfig(0x2b06420, 0x2b51c88, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/openshift/machine-config-operator/cmd/machine-config-daemon/firstboot_complete_machineconfig.go:39 +0x16f
main.executeFirstbootCompleteMachineConfig(0x2b06420, 0x2b51c88, 0x0, 0x0)
        /go/src/github.com/openshift/machine-config-operator/cmd/machine-config-daemon/firstboot_complete_machineconfig.go:43 +0x53
github.com/spf13/cobra.(*Command).execute(0x2b06420, 0x2b51c88, 0x0, 0x0, 0x2b06420, 0x2b51c88)
        /go/src/github.com/openshift/machine-config-operator/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2b066c0, 0xc0006d1f78, 0x4062c5, 0xc000100058)
        /go/src/github.com/openshift/machine-config-operator/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/openshift/machine-config-operator/vendor/github.com/spf13/cobra/command.go:895
main.main()
        /go/src/github.com/openshift/machine-config-operator/cmd/machine-config-daemon/main.go:27 +0x31
) = ?
+++ exited with 2 +++

**Comment by olafWW** [comment]
update .. same issue also with
[root@r84n1 cluster4]# ./openshift-install version
./openshift-install 4.7.21
built from commit 23a2fe80a021a19ab4364904f6928a1f8c715dc0
release image quay.io/openshift-release-dev/ocp-release@sha256:60454c3270a61432447c752a9d5ee3e7d84cebcfd5d371eb4daa263623923dac
[root@r84n1 cluster4]#

**Comment by olafWW** [comment]
I can think we can close this flavour here , because those error's are all subsequent from the root cause

covered here
https://github.com/openshift/machine-config-operator/issues/2696

closing this issue

**Comment by olafWW** [comment]
openshift/machine-config-operator#2696
