### ISSUE TITLE
Invalid memory address or nil pointer dereference when 'computeFlavor' is unset

### ISSUE THREAD

**Issue by stephenfin** [openshift/installer#5423]
# Version

`HEAD` of `release-4.9` branch (`4.9.0-0.ci-2021-11-26-051444`)

# Platform:
openstack

IPI/UPI

# What happened?

We're seeing [failures in OpenStack jobs in CI for the 4.9 branch](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.9-e2e-openstack-parallel/1464180448484659200). This appears to have been triggered by [recent changes](https://github.com/openshift/release/pull/23995/files#diff-bf11086c39a03ec6dece79cd46a113833491cc8349ccdd3f938962319a5da7e9L74) to openstack/release, which ultimately mean we're no longer setting `computeFlavor` in the default platform settings CI configuration. Clearly we should be handling this better. Failure to do so results in the following ugliness:

```
...
INFO[2021-11-26T10:39:53Z] Installing from release registry.build03.ci.openshift.org/ci-op-2bc95lmq/release@sha256:1a536627e6287b2347bb6baaf7b80d81ac644ae3c0cc3d5b0f2c5fb0eba91441
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x3188ca6]
goroutine 1 [running]:
github.com/openshift/installer/pkg/types/openstack/validation.validateDefaultMachinePool(0x0, 0xc0009eef90, 0x16, 0x0, 0x0)
	/go/src/github.com/openshift/installer/pkg/types/openstack/validation/machinepool.go:43 +0x26
github.com/openshift/installer/pkg/types/openstack/validation.ValidatePlatform(0xc000ea3600, 0xc00112a900, 0xc0009eef60, 0xc000737b00, 0x0, 0x0, 0xc0009eef60)
	/go/src/github.com/openshift/installer/pkg/types/openstack/validation/platform.go:37 +0x2a5
github.com/openshift/installer/pkg/types/validation.validatePlatform.func7(0xc0009eef60, 0x10461d60, 0x9, 0x0)
	/go/src/github.com/openshift/installer/pkg/types/validation/installconfig.go:465 +0x4a
github.com/openshift/installer/pkg/types/validation.validatePlatform.func1(0x10461d60, 0x9, 0xd890ec0, 0xc000ea3600, 0xc000f92c58)
	/go/src/github.com/openshift/installer/pkg/types/validation/installconfig.go:444 +0x29b
github.com/openshift/installer/pkg/types/validation.validatePlatform(0xc000737c70, 0xc0009eef30, 0xc00112a900, 0xc000737b00, 0x0, 0xc0009eef30, 0x6)
	/go/src/github.com/openshift/installer/pkg/types/validation/installconfig.go:464 +0x582
github.com/openshift/installer/pkg/types/validation.ValidateInstallConfig(0xc000737b00, 0x0, 0xc000f93088, 0x40e218)
	/go/src/github.com/openshift/installer/pkg/types/validation/installconfig.go:110 +0x5a5
github.com/openshift/installer/pkg/asset/installconfig.(*InstallConfig).finish(0xc000236c30, 0x104d1668, 0x13, 0x13ce, 0x1018e980)
	/go/src/github.com/openshift/installer/pkg/asset/installconfig/installconfig.go:155 +0x99
github.com/openshift/installer/pkg/asset/installconfig.(*InstallConfig).Load(0xc000236c30, 0x11bf8ce0, 0xc000817d50, 0x11cfe258, 0xc000236c30, 0xc000236c30)
	/go/src/github.com/openshift/installer/pkg/asset/installconfig/installconfig.go:136 +0x1f3
github.com/openshift/installer/pkg/asset/store.(*storeImpl).load(0xc00097ff80, 0x11c25e28, 0xc00014c7e0, 0xc000c94a6c, 0x4, 0xc000c94a6c, 0x4, 0x0)
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:264 +0x455
github.com/openshift/installer/pkg/asset/store.(*storeImpl).load(0xc00097ff80, 0x11c25df8, 0xc0009e8d20, 0x1044b240, 0x2, 0x1044b240, 0x2, 0x0)
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:247 +0x2d7
github.com/openshift/installer/pkg/asset/store.(*storeImpl).load(0xc00097ff80, 0x11c260c8, 0x19c40f80, 0x0, 0x0, 0x2, 0x2, 0x0)
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:247 +0x2d7
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc00097ff80, 0x11c260c8, 0x19c40f80, 0x0, 0x0, 0x40b845, 0xebbc880)
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:201 +0xa45
github.com/openshift/installer/pkg/asset/store.(*storeImpl).Fetch(0xc00097ff80, 0x11c260c8, 0x19c40f80, 0x19bec720, 0x4, 0x4, 0xed932b075, 0xea829c25de2c47e1)
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:77 +0x4b
main.runTargetCmd.func1(0x7fffe2cfacc4, 0xe, 0xc00000e3d8, 0x0)
	/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:238 +0x12d
main.runTargetCmd.func2(0x19bfb0e0, 0xc000817b40, 0x0, 0x1)
	/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:265 +0xb5
github.com/spf13/cobra.(*Command).execute(0x19bfb0e0, 0xc000817b30, 0x1, 0x1, 0x19bfb0e0, 0xc000817b30)
	/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0009c98c0, 0xc000f93de8, 0x1, 0x1)
	/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:895
main.installerMain()
	/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:72 +0x2fe
main.main()
	/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:50 +0x259
Setup phase finished, prepare env for next steps 
...
```

This isn't an issue on 4.10 since we [correctly guard there](https://github.com/openshift/installer/blob/c27dd34908fdac784ffb60e1296a340348bec339/pkg/types/openstack/validation/machinepool.go#L17-L19).

# What you expected to happen?

The installer should correctly handle an unset `computeFlavor` attribute, or at least fail gracefully.

# How to reproduce it (as minimally and precisely as possible)?

TBD.

# Anything else we need to know?

-

# References

- #4333

**Comment by stephenfin** [comment]
Having dug into this further, it seems the reason this was hit in CI is because `platform.openstack.computeFlavor` was no longer defined in a generated `install-config.yaml` file due to [the aforementioned change](https://github.com/openshift/release/pull/23995/files#diff-bf11086c39a03ec6dece79cd46a113833491cc8349ccdd3f938962319a5da7e9L74). This had been masking this bug since setting that attribute resulted in us initializing `config.Platform.OpenStack.DefaultMachinePlatform` with an `openstack.MachinePool` instance and populating the `FlavorName` attribute of this struct. This no longer happens, hence the unset `DefaultMachinePlatform` attribute.

**Comment by stephenfin** [comment]
Fixed in https://github.com/openshift/installer/pull/5424 (I forgot to reference it there)
