### ISSUE TITLE
agent-config.yaml: hosts parameter is not optional as stated in the docs 

### ISSUE THREAD

**Issue by rchakode** [openshift/installer#7003]
# 4.12.7

```console
$ openshift-install version
openshift-install 4.12.7
built from commit 7c2530226516a12c37f10bc14e070f66c0f27930
release image quay.io/openshift-release-dev/ocp-release@sha256:bd712a7aa5c1763870e721f92e19104c3c1b930d1a7d550a122c0ebbe2513aee
release architecture amd64
```

# Platform:
VMware vSphere

# What happened?

According to the OpenShift documentation, the `hosts` parameters is optional in `agent-config.yaml` file : https://docs.openshift.com/container-platform/4.12/installing/installing_with_agent_based_installer/installing-with-agent-based-installer.html

With the following configuration I'm experiencing a crash when creating the ISO image.

The error does not occur if I add `hosts`. 
If I add `hosts`, that works. However, my need is to create the boot ISO to create my VMs from vSphere with DHCP. 

```
apiVersion: v1alpha1
metadata:
  name: cluster-yxdn
rendezvousIP: 10.0.155.74
```

Error message
```
DEBUG     Fetching Agent Manifests...
DEBUG       Fetching Agent PullSecret...
DEBUG         Fetching Install Config...
DEBUG         Reusing previously-fetched Install Config
DEBUG       Generating Agent PullSecret...
DEBUG       Fetching InfraEnv Config...
DEBUG         Fetching Install Config...
DEBUG         Reusing previously-fetched Install Config
DEBUG         Fetching Agent Config...
DEBUG         Reusing previously-fetched Agent Config
DEBUG       Generating InfraEnv Config...
DEBUG       Fetching NMState Config...
DEBUG         Fetching Agent Config...
DEBUG         Reusing previously-fetched Agent Config
DEBUG         Fetching Install Config...
DEBUG         Reusing previously-fetched Install Config
DEBUG       Generating NMState Config...
DEBUG       Fetching AgentClusterInstall Config...
DEBUG         Fetching Install Config...
DEBUG         Reusing previously-fetched Install Config
DEBUG       Generating AgentClusterInstall Config...
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/openshift/installer/pkg/asset/agent/manifests.(*AgentClusterInstall).Generate(0xc000ae6310, 0x5?)
        /go/src/github.com/openshift/installer/pkg/asset/agent/manifests/agentclusterinstall.go:185 +0xe85
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc0009c93b0, {0x1a81ca60, 0xc000ae6310}, {0xc000ac63aa, 0x6})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:227 +0x5fa
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc0009c93b0, {0x1a81ca90, 0xc0002d4620}, {0xc000a4d00c, 0x4})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:221 +0x75b
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc0009c93b0, {0x1a81ca30, 0xc0009ffb30}, {0x4bf26f2, 0x2})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:221 +0x75b
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc0009c93b0, {0x7f616b57a918, 0x1dbb22a0}, {0x0, 0x0})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:221 +0x75b
github.com/openshift/installer/pkg/asset/store.(*storeImpl).Fetch(0x7ffd48a143f2?, {0x7f616b57a918, 0x1dbb22a0}, {0x1db7f9c0, 0x3, 0x3})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:77 +0x48
main.runTargetCmd.func1({0x7ffd48a143f2, 0x7f})
        /go/src/github.com/openshift/installer/cmd/openshift-install/create.go:261 +0x125
main.runTargetCmd.func2(0x1db8cce0?, {0xc0009c90b0?, 0x3?, 0x3?})
        /go/src/github.com/openshift/installer/cmd/openshift-install/create.go:291 +0xe7
github.com/spf13/cobra.(*Command).execute(0x1db8cce0, {0xc0009c9050, 0x3, 0x3})
        /go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc00042e280)
        /go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:918
main.installerMain()
        /go/src/github.com/openshift/installer/cmd/openshift-install/main.go:61 +0x2b0

```

# What you expected to happen?

Create a boot ISO

# How to reproduce it (as minimally and precisely as possible)?

Use the following `agent-config.yaml` and a sample install-config.yaml to try to create an ISO image (see OpenShift docs: https://docs.openshift.com/container-platform/4.12/installing/installing_with_agent_based_installer/installing-with-agent-based-installer.html)

```
apiVersion: v1alpha1
metadata:
  name: cluster-8g7h6
rendezvousIP: 10.0.145.94
```

```console
$ openshift-install agent create image --dir=<manifests_dir>
```

# Anything else we need to know?

N/A

# References

- OpenShift docs : https://docs.openshift.com/container-platform/4.12/installing/installing_with_agent_based_installer/installing-with-agent-based-installer.html

**Comment by Ultimate-etamitlU** [comment]
@rchakode ,  I tried to recreate this for a SNO config and I can create an ISO, no issues to create ISO with the configs shared to the documentation.

Need to know how many nodes you are declaring where you are facing this issue?

**Comment by rchakode** [comment]
Hi @Ultimate-etamitlU,
You got the point, in my case the install-config.yaml was for a compact cluster.
The documentation is (was?) not clear about the fact that in this case (compact/HA), the `hosts` parameter is required.

From my point of view the suggested update of the documentation shall be *more explicit* on the fact that the parameter is optional only for SNO, and not for HA or compact clusters.

Thank you!

R.

**Comment by Ultimate-etamitlU** [comment]
@rchakode Alright, I have made the change (#[62594](https://github.com/openshift/openshift-docs/pull/62594/commits/c92035c69a7d1ac143d44feb8c219ff5669ca3d3)) to have it specified.  Let me check if I can get this changed as soon as possible.

**Comment by rchakode** [comment]
Sounds good, thank you.

**Comment by rchakode** [comment]
remove-lifecycle rotten

**Comment by Ultimate-etamitlU** [comment]
I see with 4.13+ this is no longer an issue. If you have dhcp addressing available it's just agent configuration would need to have the rendezvous host IP defined. Rest can be ignored so the host config becomes optional now with DHCP introduction as it seems.
