### ISSUE TITLE
vSphere wizard broken

### ISSUE THREAD

**Issue by BlaineEXE** [openshift/installer#7040]
# Version

```console
$ openshift-install version
openshift-install 4.12.9
built from commit 15d8ffe8fa3a5ab2f36f7e0a54126c98733aaf25
release image quay.io/openshift-release-dev/ocp-release@sha256:96bf74ce789ccb22391deea98e0c5050c41b67cc17defbb38089d32226dba0b8
release architecture amd64
```
Strangely, this reports amd64 despite being the arm64 install.

# Platform:
vsphere

Please specify:
* IPI (automated install with `openshift-install`. If you don't know, then it's IPI)

# What happened?

`openshift-install create install-config` with vSphere wizard results in config that is broken (panics) for the resultant `openshift-install create` command.

```
panic: template: template:40:15: executing "template" at <.CloudCreds.VSphere.VCenter>: can't evaluate field VCenter in type *[]*manifests.VSphereCredsSecretData

goroutine 1 [running]:
github.com/openshift/installer/pkg/asset/manifests.applyTemplateData({0x140002c8900, 0x80c, 0x105e9a249?}, {0x11c453960, 0x140010fca00})
        /go/src/github.com/openshift/installer/pkg/asset/manifests/operators.go:178 +0x1cc
github.com/openshift/installer/pkg/asset/manifests.(*Openshift).Generate(0x14000c35488, 0x5?)
        /go/src/github.com/openshift/installer/pkg/asset/manifests/openshift.go:258 +0x1a44
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0x140010b67b0, {0x11d46f9d0, 0x14000c35488}, {0x14000fdc060, 0x6})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:227 +0x500
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0x140010b67b0, {0x11d46f3d0, 0x14000c353b0}, {0x14000cb5b3c, 0x4})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:221 +0x60c
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0x140010b67b0, {0x11d46f3a0, 0x14000c7a160}, {0x105e199fb, 0x2})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:221 +0x60c
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0x140010b67b0, {0x12a197358, 0x1207a2ce0}, {0x0, 0x0})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:221 +0x60c
github.com/openshift/installer/pkg/asset/store.(*storeImpl).Fetch(0x16d0b3600?, {0x12a197358, 0x1207a2ce0}, {0x12078a580, 0x8, 0x8})
        /go/src/github.com/openshift/installer/pkg/asset/store/store.go:77 +0x3c
main.runTargetCmd.func1({0x16d0b3600, 0x13})
        /go/src/github.com/openshift/installer/cmd/openshift-install/create.go:261 +0xf4
main.runTargetCmd.func2(0x120790540?, {0x14000407060?, 0x2?, 0x2?})
        /go/src/github.com/openshift/installer/cmd/openshift-install/create.go:291 +0xfc
github.com/spf13/cobra.(*Command).execute(0x120790540, {0x14000407020, 0x2, 0x2})
        /go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x1400102a280)
        /go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:918
main.installerMain()
        /go/src/github.com/openshift/installer/cmd/openshift-install/main.go:61 +0x224
main.main()
        /go/src/github.com/openshift/installer/cmd/openshift-install/main.go:38 +0xc8
                                                                 
```

# What you expected to happen?
Wizard should result in working install.

# How to reproduce it (as minimally and precisely as possible)?
Run wizard for vSphere, then try to install.

# Anything else we need to know?

# References

**Comment by BlaineEXE** [comment]
It could be that this isn't an issue with the wizard, but the vSphere deployer is still panic-ing at deploy time with deprecated configs, and there are not enough resources for me to understand how to use the new config structure.

**Comment by BlaineEXE** [comment]
I think I may have created this scenario by upgrading my openshift-install version and trying to restart a failed install that had already created templates.
