### ISSUE TITLE
vsphereprivate plugin crashes while trying to import the ova file

### ISSUE THREAD

**Issue by syangsao** [openshift/installer#7181]
# Version

```console
$ openshift-install version
./openshift-install 4.11.39
built from commit 84dcd4dad2ff22d4689da0b84cd210aa4c1e8172
release image quay.io/openshift-release-dev/ocp-release@sha256:3545730c2018e0b092d6132b31068e517cbe99b99c52c54f2a9afad61e051e3d
release architecture amd64
```

# Platform:

vSphere 7.0.3 (20150588)
IPI installation

# What happened?

IPI installation on vSphere fails with the following message:

```
DEBUG vsphere_tag.tag: Creation complete after 0s [id=urn:vmomi:InventoryServiceTag:d7f44fb3-2071-4f1c-988b-03bcfd88a3a2:GLOBAL]
DEBUG vsphere_folder.folder[0]: Creating...
DEBUG vsphere_folder.folder[0]: Creation complete after 0s [id=group-v14004]
DEBUG vsphereprivate_import_ova.import: Creating...
ERROR
ERROR Error: Plugin did not respond
ERROR
ERROR   with vsphereprivate_import_ova.import,
ERROR   on main.tf line 43, in resource "vsphereprivate_import_ova" "import":
ERROR   43: resource "vsphereprivate_import_ova" "import" {
ERROR
ERROR The plugin encountered an error, and failed to respond to the
ERROR plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
ERROR more details.
DEBUG
DEBUG Stack trace from the terraform-provider-vsphereprivate plugin:
DEBUG
DEBUG panic: runtime error: invalid memory address or nil pointer dereference
DEBUG [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x10ff8e8]
DEBUG
DEBUG goroutine 50 [running]:
DEBUG main.findImportOvaParams(0xc00013d340, {0xc000130fb0, 0xa}, {0xc000130fa0, 0x3}, {0xc000187600, 0x1e}, {0xc000130fd0, 0xa}, {0xc000131020, ...}, ...)
DEBUG 	/go/src/github.com/openshift/installer/terraform/providers/vsphereprivate/resource_vsphereprivate_import_ova.go:232 +0xe08
DEBUG main.resourceVSpherePrivateImportOvaCreate(0x0?, {0x1218b20?, 0xc0003af2c0})
DEBUG 	/go/src/github.com/openshift/installer/terraform/providers/vsphereprivate/resource_vsphereprivate_import_ova.go:330 +0x3e5
DEBUG github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x12d0380?, {0x183ca90?, 0xc000480e00?}, 0x2?, {0x1218b20?, 0xc0003af2c0?})
DEBUG 	/go/src/github.com/openshift/installer/terraform/providers/vsphereprivate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:318 +0x178
DEBUG github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000483420, {0x183ca90, 0xc000480e00}, 0xc00050b490, 0xc00007f4c0, {0x1218b20, 0xc0003af2c0})
DEBUG 	/go/src/github.com/openshift/installer/terraform/providers/vsphereprivate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x6f1
DEBUG github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000121068, {0x183ca90, 0xc000480e00}, 0xc000239770)
DEBUG 	/go/src/github.com/openshift/installer/terraform/providers/vsphereprivate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x9aa
DEBUG github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00007e640, {0x183cb38?, 0xc000539d10?}, 0x14fe380?)
DEBUG 	/go/src/github.com/openshift/installer/terraform/providers/vsphereprivate/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0x6c
DEBUG github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x151ae80?, 0xc00007e640}, {0x183cb38, 0xc000539d10}, 0xc0000939e0, 0x0)
DEBUG 	/go/src/github.com/openshift/installer/terraform/providers/vsphereprivate/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
DEBUG google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003b8380, {0x18402e0, 0xc0002c8a80}, 0xc00015f100, 0xc000539bf0, 0x221e8e0, 0x0)
DEBUG 	/go/src/github.com/openshift/installer/terraform/providers/vsphereprivate/vendor/google.golang.org/grpc/server.go:1194 +0xc8f
DEBUG google.golang.org/grpc.(*Server).handleStream(0xc0003b8380, {0x18402e0, 0xc0002c8a80}, 0xc00015f100, 0x0)
DEBUG 	/go/src/github.com/openshift/installer/terraform/providers/vsphereprivate/vendor/google.golang.org/grpc/server.go:1517 +0xa1b
DEBUG google.golang.org/grpc.(*Server).serveStreams.func1.2()
DEBUG 	/go/src/github.com/openshift/installer/terraform/providers/vsphereprivate/vendor/google.golang.org/grpc/server.go:859 +0x98
DEBUG created by google.golang.org/grpc.(*Server).serveStreams.func1
DEBUG 	/go/src/github.com/openshift/installer/terraform/providers/vsphereprivate/vendor/google.golang.org/grpc/server.go:857 +0x28a
DEBUG
DEBUG Error: The terraform-provider-vsphereprivate plugin crashed!
DEBUG
DEBUG This is always indicative of a bug within the plugin. It would be immensely
DEBUG helpful if you could report the crash with the plugin's maintainers so that it
DEBUG can be fixed. The output above should help diagnose the issue.
DEBUG
ERROR failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "pre-bootstrap" stage: failed to create cluster: failed to apply Terraform: exit status 1
ERROR
ERROR Error: Plugin did not respond
ERROR
ERROR   with vsphereprivate_import_ova.import,
ERROR   on main.tf line 43, in resource "vsphereprivate_import_ova" "import":
ERROR   43: resource "vsphereprivate_import_ova" "import" {
ERROR
ERROR The plugin encountered an error, and failed to respond to the
ERROR plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
ERROR more details.
ERROR
```

# What you expected to happen?

Installation should be able to upload the ova file but if not, at least report why and not crash the plugin.

# How to reproduce it (as minimally and precisely as possible)?

1.  Create an install-config using the following command to verify vCenter credentials and access:
```
./openshift-install create install-config
```

2.  Verified the install-config.yaml with no changes in the same directory and then ran the following command:

```
./openshift-install create cluster --log-level=debug
```

# Anything else we need to know?

This seems to occur with the 4.12 installer as well.  

I have been able to install OCP 4.11.x in this vSphere cluster before using the IPI installation method.

**Comment by syangsao** [comment]
[openshift_install.log](https://github.com/openshift/installer/files/11466494/openshift_install.log)

**Comment by syangsao** [comment]
[install-config.txt](https://github.com/openshift/installer/files/11466509/install-config.txt)

install-config.yaml file generated and used

**Comment by syangsao** [comment]
Completely restarting the vSphere environment - Shutting down vCenter, ESXi hosts and starting them back up addressed this issue.
