### ISSUE TITLE
Installer OOM while waiting for OS image download

### ISSUE THREAD

**Issue by sjug** [openshift/installer#804]
# Version

```console
$ openshift-install version
bin/openshift-install v0.5.0-master-36-gb4f5ceb6bfde8d3dc0e29f708e0494488ea37ee0
Terraform v0.11.10
$ ~/.terraform.d/plugins/terraform-provider-libvirt -version  # only needed if you're using libvirt
/home/jugs/.terraform.d/plugins/terraform-provider-libvirt was not built correctly
Compiled against library: libvirt 4.9.0
Using library: libvirt 4.9.0
Running hypervisor: QEMU 3.0.0
Running against daemon: 4.9.0
```

# Platform (aws|libvirt|openstack):

libvirt

# What happened?

Tried to `create cluster`, waiting for >20/30m for the OS image to download, installer ran out of memory.

```
INFO Fetching OS image...
DEBUG Unpacking OS image into "/home/jugs/.cache/openshift-install/libvirt/image/caccc814cc0cad480dd04d8732093683"...
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x1a04564, 0x16)
        /usr/lib/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc1c8000000, 0x58000000, 0x2d68f58)
        /usr/lib/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x2d3d2e0, 0x58000000, 0x280021d6c1, 0x7fc4127fb9d8)
        /usr/lib/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x2d3d2e0, 0x2a500, 0x0)
        /usr/lib/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x2d3d2e0, 0x2a500, 0x2d68f68, 0x0)
        /usr/lib/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x2d3d2e0, 0x2a500, 0xffffffffffff0101, 0x7fc4127fbab8)
        /usr/lib/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
        /usr/lib/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x2d3d2e0, 0x2a500, 0x7fc412010101, 0x440d50)
        /usr/lib/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x549ffe00, 0x460101, 0xc199248000)
        /usr/lib/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
        /usr/lib/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0xc0004e8180)
        /usr/lib/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/lib/go/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/go/src/runtime/asm_amd64.s:311 fp=0xc00071c808 sp=0xc00071c800 pc=0x4716b0
runtime.mallocgc(0x549ffe00, 0x167ede0, 0x50b801, 0xc00071c8e0)
        /usr/lib/go/src/runtime/malloc.go:913 +0x896 fp=0xc00071c8a8 sp=0xc00071c808 pc=0x428006
runtime.makeslice(0x167ede0, 0x549ffe00, 0x549ffe00, 0x0, 0xc00071c958, 0x7eb046)
        /usr/lib/go/src/runtime/slice.go:70 +0x77 fp=0xc00071c8d8 sp=0xc00071c8a8 pc=0x45c6a7
bytes.makeSlice(0x549ffe00, 0x0, 0x0, 0x0)
        /usr/lib/go/src/bytes/buffer.go:231 +0x6d fp=0xc00071c918 sp=0xc00071c8d8 pc=0x4f50ed
bytes.(*Buffer).grow(0xc0003b6000, 0x200, 0x15280000)
        /usr/lib/go/src/bytes/buffer.go:144 +0x15a fp=0xc00071c968 sp=0xc00071c918 pc=0x4f4a5a
bytes.(*Buffer).ReadFrom(0xc0003b6000, 0x1bdc140, 0xc0005aa0a0, 0x7fc41064a238, 0xc0003b6000, 0x1)
        /usr/lib/go/src/bytes/buffer.go:204 +0x4b fp=0xc00071c9d8 sp=0xc00071c968 pc=0x4f4eeb
io.copyBuffer(0x1bd8e20, 0xc0003b6000, 0x1bdc140, 0xc0005aa0a0, 0x0, 0x0, 0x0, 0x4248cb, 0xc000030000, 0x17bba40)
        /usr/lib/go/src/io/io.go:388 +0x303 fp=0xc00071ca48 sp=0xc00071c9d8 pc=0x48a803
io.Copy(0x1bd8e20, 0xc0003b6000, 0x1bdc140, 0xc0005aa0a0, 0xc00071caf8, 0x4f4e47, 0xc0004b08d6)
        /usr/lib/go/src/io/io.go:364 +0x5a fp=0xc00071caa8 sp=0xc00071ca48 pc=0x48a4ba
net/http.(*transferWriter).writeBody(0xc0005aa0a0, 0x1bd8e20, 0xc0003b6000, 0x2, 0x2)
        /usr/lib/go/src/net/http/transfer.go:360 +0x513 fp=0xc00071cb50 sp=0xc00071caa8 pc=0x7ed283
net/http.(*Response).Write(0xc00071ce38, 0x1bd8e20, 0xc0003b6000, 0xc00051a040, 0x1be4960)
        /usr/lib/go/src/net/http/response.go:322 +0x440 fp=0xc00071cd50 sp=0xc00071cb50 pc=0x7e58e0
net/http/httputil.DumpResponse(0xc00071ce38, 0xc00071ce01, 0x1be4960, 0xc000602000, 0xc00071ce98, 0x427a5f, 0xc00090b0b0)
        /usr/lib/go/src/net/http/httputil/dump.go:303 +0xc2 fp=0xc00071cdd8 sp=0xc00071cd50 pc=0xea73e2
github.com/openshift/installer/vendor/github.com/gregjones/httpcache.(*Transport).RoundTrip.func1(0x1bd8e40, 0xc00090b0b0)
        /home/jugs/go/src/github.com/openshift/installer/vendor/github.com/gregjones/httpcache/httpcache.go:238 +0xd2 fp=0xc00071ced8 sp=0xc00071cdd8 pc=0xeab6b2
github.com/openshift/installer/vendor/github.com/gregjones/httpcache.(*cachingReadCloser).Read(0xc00055c300, 0xc000868000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        /home/jugs/go/src/github.com/openshift/installer/vendor/github.com/gregjones/httpcache/httpcache.go:537 +0x1ee fp=0xc00071cf60 sp=0xc00071ced8 pc=0xeab53e
io.copyBuffer(0x1bdaa20, 0xc0004f4018, 0x7fc41064a158, 0xc00055c300, 0xc000868000, 0x8000, 0x8000, 0xc00071d040, 0x10, 0xc00071d038)
        /usr/lib/go/src/io/io.go:402 +0x125 fp=0xc00071cfd0 sp=0xc00071cf60 pc=0x48a625
io.Copy(0x1bdaa20, 0xc0004f4018, 0x7fc41064a158, 0xc00055c300, 0xc0004f4018, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:364 +0x5a fp=0xc00071d030 sp=0xc00071cfd0 pc=0x48a4ba
github.com/openshift/installer/pkg/tfvars/libvirt.cacheImage(0x7fc41064a158, 0xc00055c300, 0xc0000bed20, 0x52, 0x0, 0x0)
        /home/jugs/go/src/github.com/openshift/installer/pkg/tfvars/libvirt/cache.go:151 +0x439 fp=0xc00071d110 sp=0xc00071d030 pc=0x12758c9
github.com/openshift/installer/pkg/tfvars/libvirt.(*Libvirt).UseCachedImage(0xc000350578, 0x1bdaa60, 0xc000532900)
        /home/jugs/go/src/github.com/openshift/installer/pkg/tfvars/libvirt/cache.go:78 +0x685 fp=0xc00071d308 sp=0xc00071d110 pc=0x1274cd5
github.com/openshift/installer/pkg/tfvars.TFVars(0xc00056a1e0, 0xc0008cc000, 0x21623, 0xc00085e000, 0x79c, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/jugs/go/src/github.com/openshift/installer/pkg/tfvars/tfvars.go:111 +0x583 fp=0xc00071d7e8 sp=0xc00071d308 pc=0x1277283
github.com/openshift/installer/pkg/asset/cluster.(*TerraformVariables).Generate(0x2d32480, 0xc0004dcc60, 0xc00065da98, 0x2)
        /home/jugs/go/src/github.com/openshift/installer/pkg/asset/cluster/tfvars.go:53 +0x250 fp=0xc00071d8c8 sp=0xc00071d7e8 pc=0x1278ff0
github.com/openshift/installer/pkg/asset.(*StoreImpl).fetch(0xc000504b10, 0x1be7f60, 0x2d32480, 0x0, 0x0, 0x17e8500, 0x18358c0)
        /home/jugs/go/src/github.com/openshift/installer/pkg/asset/store.go:217 +0x7e7 fp=0xc00071db08 sp=0xc00071d8c8 pc=0xf395a7
github.com/openshift/installer/pkg/asset.(*StoreImpl).Fetch(0xc000504b10, 0x1be7f60, 0x2d32480, 0x1be7f60, 0x2d32480)
        /home/jugs/go/src/github.com/openshift/installer/pkg/asset/store.go:81 +0x4b fp=0xc00071db60 sp=0xc00071db08 pc=0xf37cdb
main.runTargetCmd.func1(0x2ce2b40, 0xc00051a7f0, 0x0, 0x1, 0x0, 0x0)
        /home/jugs/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:136 +0x17f fp=0xc00071dca0 sp=0xc00071db60 pc=0x153031f
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).execute(0x2ce2b40, 0xc00051a7c0, 0x1, 0x1, 0x2ce2b40, 0xc00051a7c0)
        /home/jugs/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:762 +0x473 fp=0xc00071dd90 sp=0xc00071dca0 pc=0x5e4bc3
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000158c80, 0x4, 0x0, 0xc000159b80)
        /home/jugs/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:852 +0x2fd fp=0xc00071ded0 sp=0xc00071dd90 pc=0x5e55bd
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000158c80, 0xc00002ff40, 0x1)
        /home/jugs/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:800 +0x2b fp=0xc00071df00 sp=0xc00071ded0 pc=0x5e529b
main.main()
        /home/jugs/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:32 +0x17e fp=0xc00071df98 sp=0xc00071df00 pc=0x152e7ae
runtime.main()
        /usr/lib/go/src/runtime/proc.go:201 +0x207 fp=0xc00071dfe0 sp=0xc00071df98 pc=0x448597
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00071dfe8 sp=0xc00071dfe0 pc=0x473791

goroutine 19 [chan receive, 1 minutes]:
github.com/openshift/installer/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2d369c0)
        /home/jugs/go/src/github.com/openshift/installer/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/openshift/installer/vendor/github.com/golang/glog.init.0
        /home/jugs/go/src/github.com/openshift/installer/vendor/github.com/golang/glog/glog.go:410 +0x203
goroutine 90 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7fc4191fde30, 0x72, 0xc00008c870)
        /usr/lib/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00055c298, 0x72, 0xffffffffffffff00, 0x1bdc260, 0x2ce87c0)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00055c298, 0xc0005ee000, 0x8000, 0x8000)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00055c280, 0xc0005ee000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00055c280, 0xc0005ee000, 0x8000, 0x8000, 0x4248cb, 0xc000030000, 0x17bb6c0)
        /usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0005128c0, 0xc0005ee000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc000504450, 0x1bda720, 0xc0005128c0, 0x5, 0xc0005128c0, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc00051f180, 0x1a95417, 0xc00051f2a0, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc00051f180, 0xc00049f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:1145 +0xf1
bufio.(*Reader).Read(0xc0004d8900, 0xc00024e498, 0x9, 0x9, 0xc0004ca700, 0xc00008cc58, 0xc00008cc70)
        /usr/lib/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x1bd8dc0, 0xc0004d8900, 0xc00024e498, 0x9, 0x9, 0x9, 0xc00008ccf8, 0x7dc3fb, 0xc0004d8960)
        /usr/lib/go/src/io/io.go:310 +0x88
io.ReadFull(0x1bd8dc0, 0xc0004d8900, 0xc00024e498, 0x9, 0x9, 0xc00008cd28, 0x7dc30d, 0xc00008cfb8)
        /usr/lib/go/src/io/io.go:329 +0x58
net/http.http2readFrameHeader(0xc00024e498, 0x9, 0x9, 0x1bd8dc0, 0xc0004d8900, 0x0, 0x0, 0xc0008f4930, 0x0)
        /usr/lib/go/src/net/http/h2_bundle.go:1545 +0x7b
net/http.(*http2Framer).ReadFrame(0xc00024e460, 0xc0008f4930, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/h2_bundle.go:1803 +0xa3
net/http.(*http2clientConnReadLoop).run(0xc00008cfb8, 0x1a94e98, 0xc0008c07b8)
        /usr/lib/go/src/net/http/h2_bundle.go:8261 +0x9e
net/http.(*http2ClientConn).readLoop(0xc00054d880)
        /usr/lib/go/src/net/http/h2_bundle.go:8189 +0x76
created by net/http.(*http2Transport).newClientConn
        /usr/lib/go/src/net/http/h2_bundle.go:7264 +0x636
```

# What you expected to happen?

The image to be fetched and installation to continue.

# How to reproduce it (as minimally and precisely as possible)?

Basic install procedure only using env vars and libvirt.

```console
$ export OPENSHIFT_INSTALL_PLATFORM=libvirt
$ export OPENSHIFT_INSTALL_BASE_DOMAIN=tt.testing
$ export OPENSHIFT_INSTALL_CLUSTER_NAME=test1
$ export OPENSHIFT_INSTALL_LIBVIRT_URI=qemu+tcp://192.168.122.1/system
$ export OPENSHIFT_INSTALL_PULL_SECRET_PATH=${ABS_PATH}
$ export OPENSHIFT_INSTALL_EMAIL_ADDRESS=sejug@redhat.com
$ bin/openshift-install create cluster --log-level=debug
```

# Anything else we need to know?

N/A

# References

N/A

**Comment by miabbott** [comment]
I saw something similar; had to reboot my host to free up enough memory to get past this.

**Comment by sjug** [comment]
I haven't rebooted yet, but I have like 8GB free? It needs half my system memory to download an image?

**Comment by wking** [comment]
Dup of #610.  I'd worked up streaming for our cache library (#645), but we may be dropping HTTP Cache support altogether (#687).

/close
