### ISSUE TITLE
runtime panic deleting cluster on libvirt

### ISSUE THREAD

**Issue by jcantrill** [openshift/installer#821]
# Version

```
$ ./bin/openshift-install version
./bin/openshift-install v0.5.0-master-36-gb4f5ceb6bfde8d3dc0e29f708e0494488ea37ee0
Terraform v0.11.8

$ ~/.terraform.d/plugins/terraform-provider-libvirt -version
/home/jeff.cantrill/.terraform.d/plugins/terraform-provider-libvirt was not built correctly
Compiled against library: libvirt 2.2.1
Using library: libvirt 2.2.1
Running hypervisor: QEMU 2.7.1
Running against daemon: 2.2.1

```

# Platform (aws|libvirt|openstack): libvirt

Enter text here.

# What happened?
```
$ ./bin/openshift-install destroy cluster --dir ~/tmp/installer
INFO Deleted domain                                domain=test1-master-0
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xdeadbef7 pc=0x7f52123897c8]

runtime stack:
runtime.throw(0x199ccaf, 0x2a)
	/home/jeff.cantrill/apps/go/go1.10.5/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	/home/jeff.cantrill/apps/go/go1.10.5/src/runtime/signal_unix.go:372 +0x28e

goroutine 1 [syscall]:
runtime.cgocall(0x14a0f50, 0xc42002f960, 0x158c640)
	/home/jeff.cantrill/apps/go/go1.10.5/src/runtime/cgocall.go:128 +0x64 fp=0xc42002f930 sp=0xc42002f8f8 pc=0x41c4d4
github.com/openshift/installer/vendor/github.com/libvirt/libvirt-go._Cfunc_virDomainFreeWrapper(0x462cbc0, 0xc42003b5e0, 0xc400000000)
	_cgo_gotypes.go:3409 +0x4d fp=0xc42002f960 sp=0xc42002f930 pc=0x13bcced
github.com/openshift/installer/vendor/github.com/libvirt/libvirt-go.(*Domain).Free.func1(0x462cbc0, 0xc42003b5e0, 0xc42002f9f8)
	/home/jeff.cantrill/go/src/github.com/openshift/installer/vendor/github.com/libvirt/libvirt-go/domain.go:864 +0xd7 fp=0xc42002f998 sp=0xc42002f960 pc=0x1420e97
github.com/openshift/installer/vendor/github.com/libvirt/libvirt-go.(*Domain).Free(0xc4201b2be0, 0x2, 0x2)
	/home/jeff.cantrill/go/src/github.com/openshift/installer/vendor/github.com/libvirt/libvirt-go/domain.go:864 +0x4c fp=0xc42002fa08 sp=0xc42002f998 pc=0x13e471c
github.com/openshift/installer/pkg/destroy/libvirt.deleteDomainsSinglePass(0xc4201b2bc8, 0xc42000ce20, 0x1b17fe0, 0xc420098060, 0xc42002fb00, 0x0, 0x0)
	/home/jeff.cantrill/go/src/github.com/openshift/installer/pkg/destroy/libvirt/libvirt.go:117 +0x525 fp=0xc42002fb18 sp=0xc42002fa08 pc=0x1444b45
github.com/openshift/installer/pkg/destroy/libvirt.deleteDomains(0xc4201b2bc8, 0xc42000ce20, 0x1b17fe0, 0xc420098060, 0x0, 0x196aa5b)
	/home/jeff.cantrill/go/src/github.com/openshift/installer/pkg/destroy/libvirt/libvirt.go:81 +0xbe fp=0xc42002fb60 sp=0xc42002fb18 pc=0x14445be
github.com/openshift/installer/pkg/destroy/libvirt.(*ClusterUninstaller).Run(0xc4200c8330, 0xc420098060, 0x7fff5b79abf3)
	/home/jeff.cantrill/go/src/github.com/openshift/installer/pkg/destroy/libvirt/libvirt.go:62 +0xdb fp=0xc42002fbc8 sp=0xc42002fb60 pc=0x144447b
main.runDestroyCmd(0xc420145680, 0xc42000cc00, 0x0, 0x2, 0x0, 0x0)
	/home/jeff.cantrill/go/src/github.com/openshift/installer/cmd/openshift-install/destroy.go:48 +0xe2 fp=0xc42002fc90 sp=0xc42002fbc8 pc=0x1496d42
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).execute(0xc420145680, 0xc42000cbc0, 0x2, 0x2, 0xc420145680, 0xc42000cbc0)
	/home/jeff.cantrill/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:762 +0x468 fp=0xc42002fd80 sp=0xc42002fc90 pc=0x5cd2e8
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420144c80, 0x0, 0xc420145b80, 0xc420144dd0)
	/home/jeff.cantrill/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:852 +0x30a fp=0xc42002fec0 sp=0xc42002fd80 pc=0x5cdcfa
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420144c80, 0xc42002ff30, 0x1)
	/home/jeff.cantrill/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:800 +0x2b fp=0xc42002fef0 sp=0xc42002fec0 pc=0x5cd9cb
main.main()
	/home/jeff.cantrill/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:32 +0x190 fp=0xc42002ff88 sp=0xc42002fef0 pc=0x1498610
runtime.main()
	/home/jeff.cantrill/apps/go/go1.10.5/src/runtime/proc.go:198 +0x212 fp=0xc42002ffe0 sp=0xc42002ff88 pc=0x446002
runtime.goexit()
	/home/jeff.cantrill/apps/go/go1.10.5/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42002ffe8 sp=0xc42002ffe0 pc=0x4709e1

goroutine 5 [chan receive]:
github.com/openshift/installer/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x29b6520)
	/home/jeff.cantrill/go/src/github.com/openshift/installer/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/openshift/installer/vendor/github.com/golang/glog.init.0
	/home/jeff.cantrill/go/src/github.com/openshift/installer/vendor/github.com/golang/glog/glog.go:410 +0x203

```
# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by wking** [comment]
This is dying in the CGO invocation, with a sigfault in the `virDomainFree` call.  But `addr=0xdeadbef7`, so we're not passing a `NULL` pointer.  So I dunno.  How reproducible is this for you?  Maybe you can set `ulimit -c unlimited` and trigger this crash to get more detail on what's going wrong inside libvirt?

**Comment by jcantrill** [comment]
Closing as unable to duplicate on 0.7.0
